version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: change-me
      JWT_SECRET_KEY: change-me-too
      DATABASE_URL: mongodb+srv://gowtham:JBwPSaL4vDab5qS6@cluster0.pudoe.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&authSource=admin
      MONGODB_DB_NAME: circlk
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      PLATFORM_FEE_PERCENT: 5.0
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "5000:5000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    environment:
      VITE_API_BASE: http://localhost:5000/api
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  frontend_node_modules:
